export const DEMO_TOUR_STEPS = [
  { title: 'Dashboard', description: 'Review KPIs, charts, and critical attention items.', to: '/dashboard' },
  { title: 'Amazon Order #1001', description: 'Open the hero order and start the interactive workflow.', to: '/orders/1001' },
  { title: 'SKU Mapping', description: 'Map marketplace SKUs to internal RUG SKUs.', to: '/sku-mapping' },
  { title: 'Inventory Reservation', description: 'See reserved vs free stock for RUG-1001.', to: '/inventory' },
  { title: 'Warehouse Picking', description: 'Start and confirm pick for Order #1001.', to: '/warehouse/pick-pack' },
  { title: 'Packing', description: 'Packing queue and proof upload.', to: '/warehouse/packing' },
  { title: 'Courier Reference', description: 'Manually map AWB/QR from India courier portal.', to: '/courier-references' },
  { title: 'Label Generation', description: 'Generate and print internal shipping label.', to: '/labels' },
  { title: 'India Dispatch', description: 'Dispatch from India and move stock in transit.', to: '/warehouse/dispatch' },
  { title: 'USA Receipt', description: 'Confirm physical receipt before USA stock is available.', to: '/warehouse/usa-receipts' },
  { title: 'Shipment', description: 'Customer fulfilment shipment and tracking.', to: '/shipments' },
  { title: 'True Cost', description: 'Revenue vs estimated and actual costs.', to: '/finance/costing' },
  { title: 'Profitability', description: 'Order #1001 profit story — ₹6,350 / 31.75%.', to: '/finance/profitability' },
  { title: 'Reports', description: 'Management reports and CSV export.', to: '/reports' },
];
